services:
  # Banco de dados para Produtos
  sqlserver-products:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-products
    ports:
      - "57707:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}      
      DB_USER: ${DB_USER_PRODUCTS}
      DB_PASSWORD: ${DB_PASSWORD_PRODUCTS}
      DB_NAME: ${DB_NAME_PRODUCTS}
    volumes:
      - sql_data_products:/var/opt/mssql

  # Banco de dados para Fornecedores
  sqlserver-suppliers:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-suppliers
    ports:
      - "57708:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
      DB_USER: ${DB_USER_SUPPLIERS}
      DB_PASSWORD: ${DB_PASSWORD_SUPPLIERS}
      DB_NAME: ${DB_NAME_SUPPLIERS}
    volumes:
      - sql_data_suppliers:/var/opt/mssql

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: sellgold-zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: sellgold-kafka-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
      - zookeeper

  
  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ "bash", "-c" ]
    command: >
      kafka-topics --bootstrap-server kafka:9092 --create --topic load-product-topic --partitions 1 --replication-factor 1 &&
      kafka-topics --bootstrap-server kafka:9092 --list

  # API de Produtos
  sellgold-api-products:
    build:
      context: .
      dockerfile: SellGold.Products/Dockerfile
    container_name: sellgold-api-products
    ports:
      - "5000:8080"   # HTTP
      - "5001:8081"   # HTTPS
    environment:
      - Kafka__BootstrapServers=kafka:9092
      - DOTNET_ENVIRONMENT=Development
      # - ConnectionStrings__SellGoldProductsConnection=Server=${DB_SERVER_PRODUCTS};Database=${DB_NAME_PRODUCTS};User Id=${DB_USER_PRODUCTS};Password=${DB_PASSWORD_PRODUCTS};TrustServerCertificate=True

    depends_on:
      - sqlserver-products
      - kafka

  # API de Fornecedores
  sellgold-api-suppliers:
    build:
      context: .
      dockerfile: SellGold.Suppliers/Dockerfile
    container_name: sellgold-api-suppliers
    ports:
      - "5002:8082"   # HTTP
      - "5003:8083"   # HTTPS
    environment:
      - Kafka__BootstrapServers=kafka:9092
      - DOTNET_ENVIRONMENT=Development
      # - ConnectionStrings__SellGoldSuppliersConnection=Server=${DB_SERVER_SUPPLIERS};Database=${DB_NAME_SUPPLIERS};User Id=${DB_USER_SUPPLIERS};Password=${DB_PASSWORD_SUPPLIERS};TrustServerCertificate=True

    depends_on:
      - sqlserver-suppliers
      - kafka

volumes:
  sql_data_products:
  sql_data_suppliers: